const fs = require('fs');
const path = require('path');

/**
 * const selectElement = document.querySelector('select[name="select"]');
 * const options = selectElement.querySelectorAll('option');
 * const optionValues = Array.from(options).map(option => option.value);
 * Clean up the array by removing empty strings, current and previous month
 */

const valueUrls = [
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2006_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2007_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2008_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2009_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2010_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2011_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2012_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2013_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2014_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2015_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2016_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2017_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2018_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2019_12.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2020_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2021_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_05.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_10.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2022_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_02.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_03.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_04.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_06.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_07.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_08.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_09.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2023_11.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2024_00.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2024_01.txt",
    "releve/fichiersbrut/sauvegardes/fichiersMensuels/2024_02.txt"
]

console.warn(valueUrls.length);

// async function fetchAndStore(valueUrls) {
//     const folderPath = path.join(__dirname, 'responses');
//
//     for (let i = 0; i < valueUrls.length; i++) {
//         const url = valueUrls[i];
//         try {
//             const fullUrl = `http://meteo.lyc-chamson-levigan.ac-montpellier.fr/meteo/${url}`;
//             const response = await fetch(fullUrl);
//
//             if (response.ok) {
//                 // Generate a unique filename based on the URL
//                 const filename = `${url.split('/').pop()}.txt`;
//
//                 // Read response body as text
//                 const responseData = await response.text();
//
//                 // Write the response to a file
//                 fs.writeFileSync(path.join(folderPath, filename), responseData);
//                 console.log(`Response from ${fullUrl} stored in ${filename}`);
//             } else {
//                 console.error(`Error fetching ${fullUrl}: ${response.statusText}`);
//             }
//         } catch (error) {
//             console.error(`Error fetching ${url}:`, error.message);
//         }
//     }
// }
//
//
// fetchAndStore(valueUrls)
//     .then(() => console.log('All responses fetched and stored successfully.'))
//     .catch(error => console.error('Error:', error));
